### ISSUE TITLE
🐛 ESAD-UK non-PCAWG WGS donors/specimens re-name issue

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/ega-file-transfer#1]
## Describe the bug

The `ESAD-UK` project re-named some of their submitted donor and specimen IDs during Release 28 (this was brought to our attention after the Release). We transferred some of their non-PCAWG WGS data from EGA to Collaboratory _before_ this update was done, so we currently have old submitted donor IDs in the Data Repositories page. As a result, the metadata fetched from SONG Collab which is used to generate the ARGO SONG payloads, also contains the older donor/specimen ID information. We need to update the existing donor/specimen IDs in Collab SONG to match the new (re-named) donor/specimen IDs.

## Steps To Reproduce
Example: 

The donor ID `OCCAMS-AH-122` was submitted pre-Release 28. During this time, we transferred this donor's data from EGA to Collab: https://icgc.org/4qf. In Release 28, the ESAD-UK project re-named `OCCAMS-AH-122` to `f9b321ca7e0e9d738cc4bdc16df6335c03a699de6cfdc1f0aaec1d18f17654ad`. This means that a new DO ID was assigned to the updated submitter donor ID. As a result, we have the old DO ID ([DO228674](https://icgc.org/4qf)) in Collab, and the new DO ID ([DO234150](https://dcc.icgc.org/donors/DO234150)) in the Portal - both are actually the same donor.

| | submitted donor ID | ICGC DO ID | Exists in Data Repo |
|--|---|---|--|
| Before update | OCCAMS-AH-122 | [DO228674](https://dcc.icgc.org/donors/DO228674) (defunct in Portal) | [Yes](https://icgc.org/4qf) |
| After update | f9b321ca7e0e9d738cc4bdc16df6335c03a699de6cfdc1f0aaec1d18f17654ad | [DO234150](https://dcc.icgc.org/donors/DO234150) | No |

As a result, when metadata from SONG Collab for an analysis ID belonging to this donor is retrieved, it still contains the old donor ID information, and this is turn was used to generate the metadata required for `sequencing_experiment` ARGO payloads:

SONG analysis belonging to this donor: https://song.cancercollaboratory.org/studies/ESAD-UK/analysis/EGAR00001193654
ARGO payload generated using metadata from this SONG Collab analysis: https://github.com/icgc-argo/argo-meta/blob/master/icgc_song_payloads/OCCAMS-GB/WGS/batch2-wgs-non-pcawg/EGAR00001193654.json

## Solution
Will need to update SONG Collab `donorSubmitterId` , `donorId` , `specimenSubmitterId` and `specimenId` fields with updated donor/specimen IDs so the metadata is consistent. This will ensure we fetch the correct metadata for ESAD-UK donors from Collab in order to generate the SONG payloads required by ARGO.

Mapping for old/new donor/specimen IDs provided by ESAD-UK project: https://docs.google.com/spreadsheets/d/1AiEkO7W-bC8EYhKPP4lEsYIBGbtrwKxuc0C2fAAadnk/edit?usp=sharing

Dec 16, 2020 - Discussion with Rob. 
1. Create an `Update` endpoint for Analyses on the Song version in ICGC. This endpoint will 
- Take a `studyId` and `donorId` 
- In submission, will take a new `donorSubmitterID`, `donorSubmitterSampleID`, 
- will replace the `donorID`, `sampleID` [whateve the correct ones from the ID Service are from the followig submitterids], `donorSubmitterID`, `donorSubmitterSampleID` in the analysis without changing the analysisID

2. Deploy that version to ICGC collab Song, and use the endpoint.
3. Deploy that version to ICGC collab Song, and use the endpoint.
4. After confirming, redeploy the Songs with the endpoint disabled for security.

**Comment by hknahal** [comment]
**Summary of old and new (re-named) donor IDs and specimen IDs:** https://docs.google.com/spreadsheets/d/1TtXr_BIv7M_BwCugxixqRP4SUoElntmxDskCn4eK4J0/edit?usp=sharing

Will need to update the following IDs in each affected SONG analysis:
- donorId
- donorSubmitterId
- specimenSubmitterId
- specimenId

Example:
SONG analysis: https://song.cancercollaboratory.org/studies/ESAD-UK/analysis/EGAR00001141753

Will need to update donor/specimen IDs in SONG to new Ids:
analysis_id | OLD donorSubmitterId | OLD donorId | NEW donorSubmitterId | NEW donorId | OLD specimenSubmitterId | OLD specimenId | NEW specimenSubmitterId | NEW specimenId
-- | -- | -- | -- | -- | -- | -- | -- | --
EGAR00001141753 | OCCAMS-AH-005 | DO10853 | b095be882857633de948faf0619072298aa64461fd058af02352f8961c273320 | DO234160 | Cou1-0068pre | SP23527 | eb8a8e0ae9092dacc59a47e6dd945ccd0c40de639ad4b383af1667a8bb1245bd | SP203783

Once the SONG analyses are updated, it's assumed re-indexing will also update the file objects? 
Example: https://dcc.icgc.org/api/v1/repository/files/FI811344

**Comment by christinayung** [comment]
Currently blocking alignment

**Comment by rtisma** [comment]
## Investigation
- the new donorIds, submitterDonorIds, specimenIds, and submitterSpecimenIds DONOT exist in song.cancercollaboratory.org.
- there are several "renames" that needs to happen (more than 300 donors) and all of them have files that are published. So simply doing a "re-submit" of the payload is NOT an option, since this would change the objectId, and therefore require a re-upload via score for all files. 
- the ids do not exist in the icgc id service  id.icgc.org
- the new ids exist in dcc.icgc.org because of the ETL. In the file repo page, they dont exist, since that page is an index of the data in song. This makes sense since song does not contain that data

## Solution
Since we cannot re-submit, this requires deep surgery. The song database must be accessed and updated since we cannot do a "re-submit", which means the existing records must be updated. Since we cannot do a "re-submit", we also need to update the id-service. Once this is all done we can continue with the regular import process. Given the large size of changes, code will be written to the existing import (as an added feature) to make this possible. Everything done here is considered a hack, and song should be fixed to support renames of submitter ids.

## Steps
- [ ] Check old ids exist
- [ ] Using spreadsheet that hardeep provided, create the ids via the id-client, in id.icgc.org
- [ ] Using spreadsheet that hardeep provided, update the song database with the new ids
- [ ] Ensure none of the old IDs exist in song. The old ids should exist in id.icgc.org and are unused
- [ ] Bring up a local/docker song with database clone of whats in prod, pointing to icgc score, and a local id server that is a clone of what is in id.icgc.org. Test the changes against that, and validate there are no errors.
- [ ] Upon my go-ahead, @hknahal updates her import payloads accordingly
- [ ] Follow regular import SOP: https://wiki.oicr.on.ca/display/icgcargotech/Importing+Legacy+ICGC+objects+into+Intermediate-Song

**Comment by hknahal** [comment]
Now that EGA transfer is complete, I was able to determine which files will need to be re-uploaded to Collab due to ID re-name issue.  
- Will need to **re-upload 414 existing files from 201 donors** in Collab along with updated SONG payloads:
- Summary table showing filtered list of existing files in Collab that need to re-uploaded: https://drive.google.com/file/d/1MUIkVDCkAMVsj1cs3MqM0LvvMt1TnfGm/view?usp=sharing

Steps to fix Collab data:
- [ ] download BAM file from Collab to VM (instead of EGA to VM)
- [ ] generate new SONG payload with updated donor/specimen ID
- [ ] upload new SONG payload to Collab. The BAM file will have a new object ID
- [ ] re-upload BAM file to Collab using new object ID
- [ ] publish new SONG payload in Collab

**Comment by hknahal** [comment]
@rtisma Instead of re-uploading the files to Collab, is it possible to delete the affected SONG payloads and analysis IDs from legacy SONG? That way, I can re-use the same analysis_id to re-generate a new SONG payload with the updated donor/specimen ID. So for example:
- delete analysis ID "EGAR00001141753" and associated SONG payload from legacy-song (https://song.cancercollaboratory.org/studies/ESAD-UK/analysis/EGAR00001141753)
- I would re-generate a new SONG payload using the same analysis ID "EGAR00001141753". This new SONG payload would look the same as the original, except I would update it with new `donorSubmitterId` and `specimenSubmitterId`.
- Since the file is already in Collab, the object ID should stay the same, so I could then publish the updated SONG payload.

I know we can't update the existing SONG payload in legacy song, so this is why I was wondering if we can just wipe the SONG analysis IDs and payloads from legacy-song so I can just re-generate the SONG payload from scratch.

**Comment by hknahal** [comment]
Discussed with Robert a plan to ensure analysis_id remains consistent in Collab and AWS SONG:
- Rob will add an "update" endpoint in Collab/AWS SONG to enable update of an analysis.
- The endpoint will take the old submitter donor/specimen ID as input and will update the SONG payload with the new submitter donor/specimen ID and DO/SP ID. 
- The following fields in the SONG payload will be updated in both Collab and AWS:
        - donorId
        - donorSubmitterId
        - specimenSubmitterId
        - specimenId

**Comment by hknahal** [comment]
Meeting with Christina on Jan 6 where we decided the following:
1. Rob will not need to create a new "update" endpoint (mentioned in comment above). Instead, we will leave the data as is in the Data Repositories page and publish a file on ICGC Portal (ie: https://docs.google.com/spreadsheets/d/1TtXr_BIv7M_BwCugxixqRP4SUoElntmxDskCn4eK4J0/edit#gid=1256054450) containing a mapping between old/new IDs for the affected ESAD-UK files.
2. Hardeep will verify that the new DO/SP IDs and correct submitter donor/specimen IDs exist in ARGO clinical.
3. Hardeep will create the intermediate-song payloads containing the correct IDs.

**Comment by hknahal** [comment]
Confirmed all donor/specimen IDs in `OLD donorSubmitterId` and `OLD specimenSubmitterId` columns in [spreadsheet](https://docs.google.com/spreadsheets/d/1TtXr_BIv7M_BwCugxixqRP4SUoElntmxDskCn4eK4J0/edit#gid=1256054450) currently exist in ARGO clinical -> will need to remove/suppress these. All of the new donor/specimen IDs (`NEW donorSubmitterId` and `NEW specimenSubmitterId`) are currently missing in ARGO clinical -> will need to add these to ARGO clinical

**Comment by hknahal** [comment]
Updated existing OCCAMS-GB intermediate-song payloads (https://github.com/icgc-argo/argo-meta/tree/master/icgc_song_payloads/OCCAMS-GB/WGS/batch2-wgs-non-pcawg) with new submitter donor/specimen IDs.

The OLD donor/specimen IDs were imported to intermediate-song already a while back, but these need to be removed (pink columns in [mapping table](https://docs.google.com/spreadsheets/d/1TtXr_BIv7M_BwCugxixqRP4SUoElntmxDskCn4eK4J0/edit?usp=sharing)). - Jon will check ARGO clinical for these and make sure they are removed.

Will also need to suppress affected analysis IDs using this endpoint: https://intermediate-song.rdpc.cancercollaboratory.org/swagger-ui.html#/Analysis/suppressAnalysisUsingPUT

**Comment by hknahal** [comment]
List of (23) analysis IDs to suppress in intermediate-song: https://docs.google.com/spreadsheets/d/1WxBcuFcsXBir6aVidf-VVFrHzuAYhnUyPOeo-omxm20/edit?usp=sharing

**Comment by hknahal** [comment]
DeleteDonors endpoint not working:

Example:
```curl -X DELETE "https://intermediate-song.rdpc.cancercollaboratory.org/studies/OCCAMS-GB/donors/DO10853" -H "accept: */*" -H "Authorization: Bearer <my token>"```

Response (500):

```cache-control: no-cache, no-store, max-age=0, must-revalidate 
 date: Thu, 14 Jan 2021 22:13:21 GMT 
 expires: 0 
 pragma: no-cache 
 server: openresty/1.15.8.2 
 status: 500 
 strict-transport-security: max-age=15724800; includeSubDomains 
 x-content-type-options: nosniff 
 x-frame-options: DENY 
 x-xss-protection: 1; mode=block ```

**Comment by hknahal** [comment]
Jon fixed all the ID re-naming issues for all affected analysis IDs.
