### ISSUE TITLE
Prepare PACA-AU EGA Data Transfer

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/ega-file-transfer#5]
Project admin (Amber) from PACA-AU sent list of confirmed ICGC donors to carryover to ARGO. The project has the required ARGO core clinical fields for these ICGC donors: https://drive.google.com/file/d/11K6Zukx0mf1ChTsjvYXO3hYFZFXYfpmE/view?usp=sharing

49 WGS donors
46 WXS donors
50 RNASeq donors

Cross-reference this list with latest [PACA-AU EGA/ICGC audit report](https://docs.google.com/spreadsheets/d/1Ugh7nnD-Xk6MgUE7RRPV0ReP1GprLIus0NGHOZDHFcM/edit?usp=sharing) to identify which files require EGA->Collab transfer.

**Comment by hknahal** [comment]
Added EGA File Accessions to `WGS donors missing in Collab` table for files that need to be transferred from EGA.

**Comment by hknahal** [comment]
PACA-AU WGS data (49 donors in total):

29 WGS donors already exist in Collab with PCAWG data, so may not need to transfer this data from EGA (waiting for confirmation from Amber). Intermediate-song payloads generated in the meantime (https://github.com/icgc-argo/argo-meta/issues/21)

20 WGS donors will need to be transferred from EGA: 
- Added list of PACA-AU files (20 WGS donors) to stage/transfer at EGA: https://github.com/icgc-argo/ega-file-transfer/blob/master/ega_operation/20201218/PACA-AU/to_stage_analysis.tsv 
- Contacted EGA to notify them of next batch to transfer (approximately 4.7 TB of data).

**Comment by rosibaj** [comment]
Discussed in planning: 
- When ready, @andricDu will complete the import. 
- Instructions are found here: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Importing+Legacy+ICGC+objects+into+Intermediate-Song

**Comment by hknahal** [comment]
Began EGA-> Collab transfer of WGS data for 20 PACA-AU donors

Details:
[Metadata from ICGC and EGA for WGS PACA-AU donors](https://drive.google.com/file/d/1MDrzCEgfju6hSxWZCmBpMMzXkqf8AmJF/view?usp=sharing)

Files to transfer from EGA -> Collab: https://github.com/icgc-argo/ega-file-transfer/blob/master/ega_operation/20201218/PACA-AU/to_stage_analysis.tsv

VM: 10.1.0.6
Queue ID: 77a87eab-07fe-422e-8637-f96ceed7ad64

**Comment by hknahal** [comment]
Cross-referenced requested whole exome PACA-AU carryover data with ICGC and EGA metadata. Table below shows summary of files at EGA for each whole exome sample.
NOTE: Same sample identifiers used for WGS, WXS and RNA-Seq data made it difficult to track down correct file at EGA, especially since library strategy is not recorded in EGA metadata.

[Metadata from ICGC and EGA for WXS PACA-AU donors](https://drive.google.com/file/d/1QTV4Sxw3fBOXEDN94xSMO1LBimDIwKUH/view?usp=sharing)

**Comment by hknahal** [comment]
Next batch of PACA-AU (WXS) data sent to EGA on Jan 14: https://github.com/icgc-argo/ega-file-transfer/blob/master/ega_operation/20210114/PACA-AU/to_stage_analysis.tsv

WGS PACA-AU EGA->Collab data transfer complete
